name: Run Ancient Owl Scraper

on:
  # Schedule to run once a day at 8:00 AM
  schedule:
    - cron: '0 8 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scrapers/ancient_owls/requirements.txt

      - name: Run the scraper
        env:
          APP_TOKEN: ${{ secrets.APP_TOKEN }}
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
        run: python scrapers/ancient_owls/ancient_owls_scraper.py

      # Optional: Commit the new data back to the repository
      - name: Commit and push if there are changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add *.csv *.json
          git commit -m "Automated scrape: Update data files" || echo "No changes to commit"
          git push
